version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
